### PR TITLE
Various querydsl fixes

### LINKED ISSUE #1443: ClassCastException when cloning BlazeJPAQuery (querydsl)
### Description

When a BlazeJPAQuery is cloned by clone Method the following error occurs:
`class com.blazebit.persistence.querydsl.Binds cannot be cast to class com.querydsl.core.types.Operation`

The AbstractBlazeJPAQuery#clone Method contains the following line (at 251)
`this.binds.addBinds(((Operation) query.binds.accept(new ReplaceVisitor<Void>(), null)).getArgs());`

The cast should be to Binds not to Operation.

### Steps to reproduce

`new BlazeJPAQuery<T>(entityManager, cbf).clone();`

### Environment

Version: 1.6.6           
JPA-Provider: Hibernate 5.6.4     
DBMS: PostgreSQL 13.3              
Application Server: Spring Boot 
QueryDSL: 5.0.0

### LINKED ISSUE #1460: Modulo operator return type clash between Querydsl and JPA
Querydsl assumes the LHS side as return type for the modulo operator. While this is true for various DB dialects, in JPA the spec states that modulo should return an Integer. As a result expressoins like `longExpression.mod(2L).eq(1L)` fail, because the parameter type for the constant is bound to an Integer. `intExpression.mod(2).eq(1)` on the other hand works fine.

While it is Hibernate/JPA that is strict about this and not Blaze-Persistence, users first run into this issue with the Blaze-Persistence Querydsl integration as normally Querydsl attempts to cast number parameters to the required parameter type.

```java
                if (parameterType != null && !parameterType.isInstance(val)) {
                    if (val instanceof Number && Number.class.isAssignableFrom(parameterType)) {
                        val = MathUtils.cast((Number) val, parameterType);
                    }
                }
```

Possible fixes:

1. Change `NumberExpression.mod` to return an `Integer` instead of a `<T>`. This will however be a breaking change in the Querydsl API and it might cause outrage under non-JPA users, because the Expression types are shared between `querydsl-jpa` and `querydsl-sql`, etc.
2. Introduce a utility method `JPAExpressions.mod(a, b)` that returns an `Integer` (could also be done in `JPQLNextExpressions`). This will not prevent migration issues for users that use `NumberExpression.mod`  on long fields, but at least give them a clear migration path.
3. Also cast the parameter values before setting them if these are uncompatible number types. While this would be consistent with Querydsl, I think it is undesirable.
4. Apply a treat operation to hint the query analyzer the desired return type of the operation.

Personally I like option 4 the best. No breaking changes, no unexpected conversions (you ask for a long, you get a long), and if you truly want an integer, you can still explicitly cast or use integers as input.

### Environment

Version:            
JPA-Provider:       
DBMS:               
Application Server:

### LINKED ISSUE #1516: Set operation of multiple BlazeJPAQuery fails during execution
### Description

Creating a union of multiple BlazeJPAQuery and executing that doesn't work.

### Expected behavior

Should produce a result

### Actual behavior

```
java.lang.IllegalStateException: Modifications to a query after connecting with a set operation is not allowed!
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.prepareForModification(AbstractCommonQueryBuilder.java:3526) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.impl.AbstractFullQueryBuilder.prepareForModification(AbstractFullQueryBuilder.java:134) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.impl.CriteriaBuilderImpl.prepareForModification(CriteriaBuilderImpl.java:48) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.with(AbstractCommonQueryBuilder.java:531) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.with(AbstractCommonQueryBuilder.java:518) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.with(AbstractCommonQueryBuilder.java:508) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$JPQLNextExpressionSerializer.visitOperation(BlazeCriteriaBuilderRenderer.java:1106) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.querydsl.core.support.SerializerBase.visit(SerializerBase.java:273) ~[querydsl-core-5.0.0.jar:na]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$JPQLNextExpressionSerializer.visit(BlazeCriteriaBuilderRenderer.java:1160) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$JPQLNextExpressionSerializer.visit(BlazeCriteriaBuilderRenderer.java:1022) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.querydsl.core.types.OperationImpl.accept(OperationImpl.java:88) ~[querydsl-core-5.0.0.jar:na]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.renderCTEs(BlazeCriteriaBuilderRenderer.java:368) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.access$400(BlazeCriteriaBuilderRenderer.java:106) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$1.visit(BlazeCriteriaBuilderRenderer.java:255) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.querydsl.core.types.SubQueryExpressionImpl.accept(SubQueryExpressionImpl.java:57) ~[querydsl-core-5.0.0.jar:na]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.serializeSubQuery(BlazeCriteriaBuilderRenderer.java:131) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.setExpressionSubqueries(BlazeCriteriaBuilderRenderer.java:841) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.renderWhere(BlazeCriteriaBuilderRenderer.java:431) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.access$800(BlazeCriteriaBuilderRenderer.java:106) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$1.visit(BlazeCriteriaBuilderRenderer.java:260) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.querydsl.core.types.SubQueryExpressionImpl.accept(SubQueryExpressionImpl.java:57) ~[querydsl-core-5.0.0.jar:na]
	at com.querydsl.core.support.FetchableSubQueryBase.accept(FetchableSubQueryBase.java:150) ~[querydsl-core-5.0.0.jar:na]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$1.visit(BlazeCriteriaBuilderRenderer.java:230) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.querydsl.core.types.OperationImpl.accept(OperationImpl.java:88) ~[querydsl-core-5.0.0.jar:na]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$1.visit(BlazeCriteriaBuilderRenderer.java:172) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.querydsl.core.types.OperationImpl.accept(OperationImpl.java:88) ~[querydsl-core-5.0.0.jar:na]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$1.visit(BlazeCriteriaBuilderRenderer.java:252) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.querydsl.core.types.SubQueryExpressionImpl.accept(SubQueryExpressionImpl.java:57) ~[querydsl-core-5.0.0.jar:na]
	at com.querydsl.core.support.FetchableSubQueryBase.accept(FetchableSubQueryBase.java:150) ~[querydsl-core-5.0.0.jar:na]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.serializeSubQuery(BlazeCriteriaBuilderRenderer.java:131) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.render(BlazeCriteriaBuilderRenderer.java:127) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.getQueryable(AbstractBlazeJPAQuery.java:223) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.createQuery(AbstractBlazeJPAQuery.java:174) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.createQuery(AbstractBlazeJPAQuery.java:165) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.querydsl.jpa.impl.AbstractJPAQuery.fetch(AbstractJPAQuery.java:242) ~[querydsl-jpa-5.0.0.jar:na]
	at com.blazebit.persistence.querydsl.SetExpressionImpl.fetch(SetExpressionImpl.java:61) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
```

### Steps to reproduce

Use a query like this `new BlazeJPAQuery<Tuple>(criteriaBuilderFactory).union(mainSelect1, mainSelect2, mainSelect3);` where the individual selects are simple queries.

### Environment

Version:            1.6.6
JPA-Provider:       Hibernate
DBMS:               -
Application Server: -

### LINKED ISSUE #1524: Support CTE's for left-nested set queries
### Description

The `StartOngoingSetOperationCriteriaBuilder` does not extend `CTEBuilder`. Therefore its currently not possible to add CTE's to a left-nested set query.

### Expected behavior
Adding CTE's to a left-nested set query is possible.

### Actual behavior

The method does not appear in the API.

### Environment

Version:            
JPA-Provider:       
DBMS:               
Application Server:

### LINKED ISSUE #1525: Bind entity shorthand does not work for complex embeddables in Querydsl
### Description

When producing a query with entity subqueries, like:

```java
    JPQLNextQuery<Tuple> select = queryFactory
            .from(selectFrom(person).where(person.id.eq(literal(1l))), new QPerson("a"))
            .from(selectFrom(person).where(person.id.eq(literal(2l))), new QPerson("b"))
            .innerJoin(selectFrom(person).where(person.id.eq(literal(3l))), new QPerson("c"))
                .on(Expressions.ONE.eq(Expressions.ONE))
            .select(new QPerson("a"), new QPerson("c"));
```

Currently the above may fail if the entity has some more complex (embeddable) mappings.

This is because the `BlazeCriteriaBuilderRenderer` does not currently utilise `JpaUtils.getEmbeddedPropertyPaths` to find the embedded property paths.

FWIW:  I also considered changing the code to use `fromEntitySubquery` instead of `fromSubquery` (and consorts) when we intend to perform an entity subquery. This would eliminate the need for the query renderer to render its own entity bindings.  However, I opted not to, because that way we can also support returning entities in set operations that are used as subquery. This is a feature that is rather difficult to support in core.

### Expected behavior
Entity subselect works in all cases.

### Actual behavior
Entity subselect does not work in all cases.

### Environment

Version:            
JPA-Provider:       
DBMS:               
Application Server:

### PR DESCRIPTION
**Pull request by jwgmeligmeyling**
## Description
Closes #1443
Closes #1460
Closes #1461
Closes #1464
Closes #1516
Closes #1524
Closes #1525

### CODE REVIEW

File: integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/BlazeCriteriaBuilderRenderer.java [hunk 1]
```diff
@@ -1457,4 +1479,72 @@ public Expression<?> visit(TemplateExpression<?> expr, BindResolverContext conte
 
     }
 
+    /**
+     * Recursively find CTE's and render these against the CriteriaBuilder.
+     *
+     * @since 1.6.7
+     */
+    private class CTERenderVisitor implements Visitor<Object, Object> {
```
Comment (beikov) [inline integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/BlazeCriteriaBuilderRenderer.java:1487]: Maybe I'm not seeing it, but can't this class be static?

File: integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQueryFactory.java [hunk 2]
```diff
@@ -16,122 +16,276 @@
...
+import java.util.Collection;
+import java.util.List;
 
 /**
  * Query factory to simplify {@link BlazeJPAQuery} instantiation.
  *
  * @author Jan-Willem Gmelig Meyling
  * @since 1.6.2
  */
-public class JPQLNextQueryFactory implements JPQLQueryFactory {
```
Comment (beikov) [inline integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQueryFactory.java:38]: The change from class to interface is incompatible and clients must recompile their code. Is this change really necessary? Maybe it's worth adding a new subclass and promote the use of that, but still keep this class around?

File: integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQuery.java [hunk 3]
```diff
@@ -35,12 +36,11 @@
  * Query interface for JPQL.Next queries
  *
  * @param <T> Query result type
- * @param <Q> Concrete query type
  * @author Jan-Willem Gmelig Meyling
  * @since 1.5.0
  */
 @SuppressWarnings("unused")
-public interface JPQLNextQuery<T, Q extends JPQLNextQuery<T, Q>> extends JPQLQuery<T> {
+public interface JPQLNextQuery<T> extends JPQLQuery<T>, ExtendedFetchable<T> {
```
Comment (beikov) [inline integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQuery.java:43]: I know it sucks, but do you think it's possible to keep around this type variable to stay compatible with the old version? We can remove the type variable in 2.0 if you want. If you say this is necessary though, I'm fine with breaking user code, but AFAICT, it's a cosmetic change.

File: integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextExpressions.java [hunk 4]
```diff
@@ -1122,7 +1123,7 @@ public static <T> Expression<T> cast(Class<T> result, Expression<?> expression)
      * @param <T> Expression type
      * @return The treated expression
      */
-    public static <T> Expression<T> treat(Class<T> result, Expression<?> expression) {
+    public static <T> SimpleOperation<T> treat(Class<T> result, Expression<?> expression) {
```
Comment (beikov) [inline integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextExpressions.java:1126]: Is this change necessary? I couldn't find uses of the method in the changed code, so maybe this turns out to be just a cosmetic change as well? If you want, we can change the signatures in 2.0.

**Review by beikov — COMMENTED** [review]
LGTM, but overall I would prefer if we could avoid signature changes. If you think we can do without signature changes, I would further suggest you compile a list of changes that you'd like to do in 2.0 in an issue and target 2.0

File: integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQueryFactory.java (hunk 2 above)
Comment (jwgmeligmeyling) [reply integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQueryFactory.java:38]: I doubt any users will currently use this class:
- Its was only recently introduced
- The documentation does not mention it or how to use it, all examples just use `new BlazeJPAQuery<>()` to construct new queries
- The class was pretty useless as it were without the signature changes.

File: integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/BlazeCriteriaBuilderRenderer.java (hunk 1 above)
Comment (jwgmeligmeyling) [reply integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/BlazeCriteriaBuilderRenderer.java:1487]: I don't think so, it needs to invoke some methods on the outer renderer.

File: integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQuery.java (hunk 3 above)
Comment (jwgmeligmeyling) [reply integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQuery.java:43]: I don't think anyone currently uses the `JPQLNextQuery` class directly, because everywhere we just returned `BlazeJPAQuery` and none of our examples mentioned this API. None of my codebases interacts with  `JPQLNextQuery` directly currently.

Comment (jwgmeligmeyling) [reply integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQuery.java:43]: We can postpone the signature change though, but then I think in 2.0 the impact will be slightly more drastic, because with the new `JPQLQueryFactory` interface people might actually start programming against `JPQLNextQuery<T, ?>` instead of `BlazeJPAQuery<T>` which would then later need to be replaced with `JPQLNextQuery<T>`.

File: integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextExpressions.java (hunk 4 above)
Comment (jwgmeligmeyling) [reply integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextExpressions.java:1126]: Not necessary no. I'll revert it.

**Comment by jwgmeligmeyling** [comment]
> I would further suggest you compile a list of changes that you'd like to do in 2.0 in an issue and target 2.0

These signature changes would be commit https://github.com/Blazebit/blaze-persistence/pull/1526/commits/13099181b965f68ef5ddcaf4583790bc3ecf7e72 in entirety.

File: integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQuery.java (hunk 3 above)
Comment (jwgmeligmeyling) [reply integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQuery.java:43]: I think eventually I would like to separate `-api` and `-impl` as separate modules in 2.0 (also to get rid of the provided scoped dependency). This is kind of a step towards that goal by properly separating API interfaces from implementation.

File: integration/querydsl/testsuite/src/test/java/com/blazebit/persistence/querydsl/BasicQueryTest.java [hunk 5]
```diff
@@ -214,10 +230,29 @@ public void testFetchCount() {
...
+                    .from(person)
+                    .select(person, person)
+                    .where(bitwiseAndLong(person.id, 1L));
+
+            assertNotNull(query.fetchResults());
+        });
+    }
+
+    public static BooleanExpression bitwiseAndLong(NumberExpression<Long> expression, long bit) {
+        NumberExpression<Long> mod = expression.divide(1L << bit).floor().mod(2L);
```
Comment (jwgmeligmeyling) [inline integration/querydsl/testsuite/src/test/java/com/blazebit/persistence/querydsl/BasicQueryTest.java:246]: According to the Postgresql documentation, `ceil` should return its input type.

However:

```
portal=# select pg_typeof(5::bigint/2::bigint);
 pg_typeof 
-----------
 bigint
(1 row)

portal=# select pg_typeof(floor(5::bigint/2::bigint));
    pg_typeof     
------------------
 double precision
```

This then causes issues with the modulo operator, failing with `Caused by: org.postgresql.util.PSQLException: ERROR: function mod(double precision, bigint) does not exist`.

Should we cast the result of `floor` or just leave it to the user to solve and just add the cast to the test here to fix the issue with Postgres?

File: integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQueryFactory.java (hunk 2 above)
Comment (beikov) [reply integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQueryFactory.java:38]: Ok, that's convincing!

File: integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQuery.java (hunk 3 above)
Comment (beikov) [reply integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextQuery.java:43]: Sounds ok to me. Please just add a note to the changelog that people will probably have to recompile code when using the new version.

File: integration/querydsl/testsuite/src/test/java/com/blazebit/persistence/querydsl/BasicQueryTest.java (hunk 5 above)
Comment (beikov) [reply integration/querydsl/testsuite/src/test/java/com/blazebit/persistence/querydsl/BasicQueryTest.java:246]: According to this (https://www.postgresql.org/docs/current/functions-math.html#id-1.5.8.9.6.2.2.9.1.1.1) it will return either numeric or double precision. Since `5/2` is a literal, PostgreSQL will probably infer `double precision` rather than `numeric`. Overall, I think this is something Hibernate 6.x should fix (can you please create an issue?). For the test, I'd say let's just cast `floor`, yes. But let's not change anything in the implementation.

Comment (jwgmeligmeyling) [reply integration/querydsl/testsuite/src/test/java/com/blazebit/persistence/querydsl/BasicQueryTest.java]: Added cast

File: integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextExpressions.java (hunk 4 above)
Comment (jwgmeligmeyling) [reply integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/JPQLNextExpressions.java]: The change was made to use in JPQLNextSerializer which initially replaced the mod operation expression with the expression returned from `treat(operator.getType(), operator)`. 

However this has since changed to simply `"TREAT_" + type.getSimpleName().toUpperCase()` because I didn't like the code.

This was a left over from that change and I have reverted it now.

**Review by beikov — APPROVED** [review]
LGTM

File: integration/querydsl/testsuite/src/test/java/com/blazebit/persistence/querydsl/BasicQueryTest.java [hunk 6]
```diff
@@ -243,7 +244,7 @@ public void testModuloLongOperation() {
     }
 
     public static BooleanExpression bitwiseAndLong(NumberExpression<Long> expression, long bit) {
-        NumberExpression<Long> mod = expression.divide(1L << bit).floor().mod(2L);
+        NumberExpression<Long> mod = castToNum(Long.class, expression.divide(1L << bit).floor()).mod(2L);
```
Comment (jwgmeligmeyling) [inline integration/querydsl/testsuite/src/test/java/com/blazebit/persistence/querydsl/BasicQueryTest.java:247]: From the remaining test failure, it appears as if MySQL does not allow `cast(x as bigint)`. I believe I am using `CAST_LONG` from the [cast and treat functions](https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/index.html#cast-and-treat-functions). Shall I just exclude the test for one or the other dialect?

Comment (jwgmeligmeyling) [reply integration/querydsl/testsuite/src/test/java/com/blazebit/persistence/querydsl/BasicQueryTest.java:247]: According to MySQL docs, `bigint` should have been fine: https://dev.mysql.com/doc/refman/8.0/en/integer-types.html
