### PR TITLE
[#1129] Add default fromString parameter conversion for JAX-RS integr…

### LINKED ISSUE #1129: EntityViewId annotation has no effect in Quarkus resource
### Description
The [Quarkus guide on using blaze-persistence](https://quarkus.io/guides/blaze-persistence) and [blaze-persistence-examples-quarkus sample project](https://github.com/Blazebit/blaze-persistence/blob/master/examples/quarkus/base/src/main/java/com/blazebit/persistence/examples/quarkus/base/resource/PersonResource.java) indicate that the annotation `com.blazebit.persistence.integration.jaxrs.EntityViewId` can be used to bind a path parameter to an entity view id. However, the annotation does not seem to have any effect.

Additionally, it is not clear whether a project needs to declare `org.glassfish.jersey.core:jersey-common` as a dependency to use this annotation. If the dependency is not declared, Quarkus gives the following warning:

```
2020-07-11 00:39:36,389 WARN  [io.qua.arc.pro.BeanArchives] (build-20) Failed to index org.glassfish.jersey.model.Parameter: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader
2020-07-11 00:39:36,389 INFO  [io.qua.arc.pro.IndexClassLookupUtils] (build-20) Class for name: org.glassfish.jersey.model.Parameter was not found in Jandex index. Please ensure the class is part of the index.
```

I noticed that `blaze-persistence-integration-jaxrs`, which contains `EntityViewId.class`, declares `jersey-common` as an optional dependency.

The annotation behaves the same regardless.

### Expected behavior
Entity view id is set to the value supplied in a path parameter.

### Actual behavior
Entity view id is null.

### Steps to reproduce
1. `git clone https://github.com/kekbur/blaze-persistence-quarkus-test.git && cd blaze-persistence-quarkus-test`
2. `./mvnw quarkus:dev`
3. `curl -H "Content-Type: application/json" -d '{"name":"Test"}' -X PUT "http://localhost:8080/persons/2c426b89-c102-45ad-8527-07cbbeb0a243"`

The PUT request above results in a `HTTP 400 - Bad Request` response, because [personUpdateView.getId() returns null](https://github.com/kekbur/blaze-persistence-quarkus-test/blob/06bf073e6c4bcd0d1b1606a3e566784bedd2b5a0/src/main/java/com/github/kekbur/blazepersistencequarkustest/resource/PersonResource.java#L52).

### Environment
Version:            1.5.0-Alpha5
JPA-Provider:       Hibernate 5.4.16.Final
DBMS:               H2
Application Framework: Quarkus 1.5.0.Final

### PR DESCRIPTION
**Pull request by Mobe91**
…ation

Fixes #1129

### CODE REVIEW

File: integration/jackson/src/main/java/com/blazebit/persistence/integration/jackson/EntityViewAwareObjectMapper.java [hunk 1]
```diff
@@ -136,12 +136,7 @@ public ObjectReader readerFor(JavaType javaType) {
         if (Collection.class.isAssignableFrom(javaType.getRawClass())) {
             return objectMapper.readerFor(javaType);
         } else {
-            return readerFor(javaType.getRawClass());
+            return objectMapper.readerFor(javaType.getRawClass());
         }
     }
-
-    public ObjectReader readerFor(Class<?> type) {
```
Comment (beikov) [inline integration/jackson/src/main/java/com/blazebit/persistence/integration/jackson/EntityViewAwareObjectMapper.java:143]: Please revert this. The idea of the method is that a user should be able to provide a custom object reader.

File: integration/quarkus/deployment/src/main/java/com/blazebit/persistence/integration/quarkus/deployment/BlazePersistenceProcessor.java [hunk 2]
```diff
@@ -148,6 +166,15 @@ void reflection(EntityViewsBuildItem entityViewsBuildItem,
                 );
             }
         }
+
+        // add fromString methods from entity view id types
+        for (EntityViewMapping entityViewMapping : entityViewConfigurationBuildItem.getEntityViewConfiguration().getEntityViewMappings()) {
+            reflectionProducer.produce(ReflectiveClassBuildItem.builder(
+                    entityViewMapping.getIdAttribute().getDeclaredType())
+                    .methods(true)
```
Comment (beikov) [inline integration/quarkus/deployment/src/main/java/com/blazebit/persistence/integration/quarkus/deployment/BlazePersistenceProcessor.java:174]: Can't you provide a specific method signature instead?

File: integration/jaxrs/src/main/java/com/blazebit/persistence/integration/jaxrs/EntityViewMessageBodyReader.java [hunk 3]
```diff
@@ -169,4 +181,46 @@ private boolean hasMatchingMediaType(MediaType mediaType) {
...
     }
+
+    /**
+     * ParamConverterProvider for default parameter conversion using fromString method if present
+     */
+    private static class FromStringParamConverterProvider implements ParamConverterProvider {
+        @Override
+        public <T> ParamConverter<T> getConverter(Class<T> clazz, Type type, Annotation[] annotations) {
+            try {
+                return new ParamConverter<>(clazz.getMethod("fromString", String.class));
```
Comment (beikov) [inline integration/jaxrs/src/main/java/com/blazebit/persistence/integration/jaxrs/EntityViewMessageBodyReader.java:192]: According to the JAX-RS specification, here is a listing in the Resteasy documentation https://docs.jboss.org/resteasy/docs/3.5.0.Final/userguide/html/StringConverter.html#d4e1480, you should also support primitive types as well as types that have a public constructor that accepts just a string. In addition to that, you should also support a static method `valueOf`.
Apart from that, it would be good to cache the `ParamConverter` in a concurrent hash map within `FromStringParamConverterProvider`

File: integration/quarkus/deployment/src/main/java/com/blazebit/persistence/integration/quarkus/deployment/BlazePersistenceProcessor.java (hunk 2 above)
Comment (Mobe91) [reply integration/quarkus/deployment/src/main/java/com/blazebit/persistence/integration/quarkus/deployment/BlazePersistenceProcessor.java:174]: No, the API does not allow for this.
