### PR TITLE
[#1393] Ensure stream/iteration processing of results works with entity views containing no collections

### LINKED ISSUE #1393: Unable to use result set streaming on version 1.6.3 with Hibernate
### Description

```
TypedQuery<View> query = viewBuilder.getQuery();
return query.getResultStream();
```

Using the above snippet works on version 1.6.0, but since moving to 1.6.3 (this is required on our end), we receive the following exception.

```
org.hibernate.exception.GenericJDBCException: could not advance using next()
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.internal.ScrollableResultsImpl.convert(ScrollableResultsImpl.java:71)
	at org.hibernate.internal.ScrollableResultsImpl.next(ScrollableResultsImpl.java:106)
	at org.hibernate.query.internal.ScrollableResultsIterator.hasNext(ScrollableResultsIterator.java:33)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:132)
	at reactor.core.publisher.FluxStream.subscribe(FluxStream.java:71)
	at reactor.core.publisher.FluxUsing.subscribe(FluxUsing.java:102)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8185)
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:208)
	at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:80)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8185)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:195)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:82)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
	at org.springframework.security.concurrent.DelegatingSecurityContextRunnable.run(DelegatingSecurityContextRunnable.java:82)
	at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.postgresql.util.PSQLException: This ResultSet is closed.
	at org.postgresql.jdbc.PgResultSet.checkClosed(PgResultSet.java:2905)
	at org.postgresql.jdbc.PgResultSet.next(PgResultSet.java:1924)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.next(HikariProxyResultSet.java)
	at org.hibernate.internal.ScrollableResultsImpl.next(ScrollableResultsImpl.java:101)
	... 26 common frames omitted
```

The temporary workaround provided by @jwgmeligmeyling worked, which is great, but we are relying on streaming here because these result sets are large. 

Here is a screenshot of the call stack: 
image

Looks like it is delegating down to hibernate's QueryImpl on 1.6.3.

### Expected behavior

This exception does not occur and we get a stream of results, just as we did on 1.6.0

### Actual behavior

Hibernate exception thrown - `org.hibernate.exception.GenericJDBCException: could not advance using next()`

### Steps to reproduce

I have created this test project - https://github.com/dsarlo-viso/blaze-web-implementation-issues - but I am unable to reproduce the issue here. Looking to get some insight in this thread into what could have possibly changed between 1.6.0 and 1.6.3 that this is now a problem for us.

### Environment

Version: 1.6.3
JPA-Provider: Hibernate 5.4.29.Final (Spring Data JPA 2.4.4)
DBMS: PostgreSQL 9.6
Application Server: Spring Boot 2.4.4

### PR DESCRIPTION
**Pull request by beikov**
## Related Issue

Fixes #1393

### CODE REVIEW

File: entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ChainingObjectBuilder.java [hunk 1]
```diff
@@ -48,19 +47,12 @@ public ChainingObjectBuilder(TupleTransformatorFactory transformatorFactory, Obj
     }
 
     @Override
-    @SuppressWarnings("unchecked")
     public T build(Object[] tuple) {
-        return (T) tuple;
+        return objectBuilder.build(transformator.transform(tuple));
```
Comment (jwgmeligmeyling) [inline entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ChainingObjectBuilder.java:51]: Is a similar fix also desired for [`LateAdditionalObjectBuilder`](https://github.com/Blazebit/blaze-persistence/blob/aca8349abd3605a56a87c6d126c146795d791848/entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/LateAdditionalObjectBuilder.java) and sorts?

Comment (beikov) [reply entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ChainingObjectBuilder.java:51]: That object builder is only used for subselect queries that fetch an attribute, but I think what we could do is modelling a SELECT with batch size 1 and subselect/multiset-fetch as normal TupleTransformer instead of as TupleListTransformer which allows more use cases to use streaming. I'll look into this.
