### PR TITLE
[#1458] Fix rendering of association joins without alias

### LINKED ISSUE #1458: Explicit join followed by implicit join for same path fails
Copying from our Slack discussion

```java
class Entity1 { @ManyToOne Entity2 entity2; }
class Entity2 { @ManyToOne Entity3 entity3; }
class Entity3 { String doesntMatter; }
```

the query

```java
query.leftJoin(qEntity1.entity2).leftJoin(qEntity1.entity2.entity3)
```

fails with

```
java.lang.IllegalArgumentException: Alias conflict [entity2=entity2, entity1_entity2=entity1.entity2]
	at com.blazebit.persistence.impl.JoinManager.getOrCreate(JoinManager.java:3744)
	at com.blazebit.persistence.impl.JoinManager.createOrUpdateNode(JoinManager.java:3658)
	at com.blazebit.persistence.impl.JoinManager.join(JoinManager.java:2590)
	at com.blazebit.persistence.impl.JoinManager.join(JoinManager.java:2514)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.joinDefault(AbstractCommonQueryBuilder.java:1863)
	at com.blazebit.persistence.impl.AbstractFullQueryBuilder.joinDefault(AbstractFullQueryBuilder.java:90)
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.renderJoins(BlazeCriteriaBuilderRenderer.java:529)
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.access$500(BlazeCriteriaBuilderRenderer.java:106)
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$1.visit(BlazeCriteriaBuilderRenderer.java:257)
	at com.querydsl.core.types.SubQueryExpressionImpl.accept(SubQueryExpressionImpl.java:57)
	at com.querydsl.core.support.FetchableSubQueryBase.accept(FetchableSubQueryBase.java:150)
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.serializeSubQuery(BlazeCriteriaBuilderRenderer.java:131)
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.render(BlazeCriteriaBuilderRenderer.java:127)
	at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.getQueryable(AbstractBlazeJPAQuery.java:223)
	at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.createQuery(AbstractBlazeJPAQuery.java:174)
	at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.fetchOne(AbstractBlazeJPAQuery.java:321)
	at com.querydsl.core.support.FetchableQueryBase.fetchFirst(FetchableQueryBase.java:51)
```

### PR DESCRIPTION
**Pull request by jwgmeligmeyling**
Render default joins with no alias (Blaze-Persistence will generate it under the hood). Previously the default alias was used which may result into alias conflicts.

Fixes #1458

### CODE REVIEW

File: core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java [hunk 1]
```diff
@@ -2582,17 +2582,17 @@ public BuilderType joinDefault(String path, String alias, JoinType type) {
         return (Z) joinOnEntitySubquery(base, clazz, alias, subqueryAlias, JoinType.RIGHT);
     }
 
-    private void checkJoinPreconditions(Object path, String alias, JoinType type) {
+    private void checkJoinPreconditions(Object path, String alias, JoinType type, boolean defaultJoin) {
```
Comment (beikov) [inline core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java:2585]: I think that `com.blazebit.persistence.impl.AbstractFullQueryBuilder#join(java.lang.String, java.lang.String, com.blazebit.persistence.JoinType, boolean, boolean)` should also use this method.

File: integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/BlazeCriteriaBuilderRenderer.java [hunk 2]
```diff
@@ -475,10 +475,13 @@ private void renderDistinct(QueryMetadata metadata, DistinctBuilder<?> criteriaB
...
                 Path<?> entityPath = (Path<?>) target;
-                if (alias == null) {
-                    alias = entityPath.getMetadata().getName();
-                }
                 boolean entityJoin = entityPath.getMetadata().isRoot();
+                String renderedExpression = renderExpression(entityPath);
+
+                // While this looks suspicious, this is actually in line with Querydsl's default behaviour in JPQLSerializer.handleJoinTarget
+                if (alias == null && entityJoin) {
+                    alias = renderedExpression;
```
Comment (beikov) [inline integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/BlazeCriteriaBuilderRenderer.java:483]: Not sure what `entityJoin` means exactly in this context, but using an entity name as alias is asking for trouble as you can see here: https://github.com/Blazebit/blaze-persistence/issues/1450

Comment (jwgmeligmeyling) [reply integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/BlazeCriteriaBuilderRenderer.java:483]: In Querydsl it is conventional, because an EntityPath is both a Path and a From:

```java
.from(QEntity.entity)
```

Renders:

```sql
FROM Entity entity
```

And:

```java
.from(QEntity.entity)
.innerJoin(QOtherEntity.otherEntity).on(QOtherEntity.otherEntity.id.eq(1))
```

Renders:

```sql
FROM Entity entity INNER JOIN OtherEntity otherEntity on otherEntity.id = 1
```

It's also conventional to create Q-class instances with a unique name:

```java
QEntity alias = new QEntity("alias");
.from(alias)
```

Renders:

```sql
FROM Entity alias
```

So in order to support these syntaxes, we need to consider the alias in the case it is a root path (in which case it is also an entity join).

However, the naming strategy for the "default" alias (`QEntity.entity`) is configurable. It is also possible to disable the default alias altogether. So I think there are plenty of ways to work around eventual issues, and these are issues that Querydsl users had to guard themselves against anyway.

Comment (beikov) [reply integration/querydsl/expressions/src/main/java/com/blazebit/persistence/querydsl/BlazeCriteriaBuilderRenderer.java:483]: Sounds good, thanks for the explanation!

**Review by beikov — APPROVED** [review]

**Comment by beikov** [comment]
Thanks!
